version: "3"

services:
  db:
    build: ./mysql/
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: my_db_db
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
